name: wemake-python-styleguide
uses: wemake-services/wemake-python-styleguide@0.15.3
on:
  push:
  workflow_dispatch:
  
with:
  reporter: 'github-pr-review'
env:
  GITHUB_TOKEN: ${{ secrets.github_token }}
